### ISSUE TITLE
图片迁移失败

### ISSUE THREAD

**Issue by Chorer** [PicGo/picgo-plugin-pic-migrater#11]
环境：
win10， PicGo 2.1.2 pic-migrater 1.1.0

插件配置：
只设置了newFileSuffix 为 new

问题描述：
markdown文件里面的图片是放在github上的，格式为：
```
![](https://raw.githubusercontent.com/Chorer/MyBlog-Pic/master/Myblogs/xxxx.jpg)
```
PicGo的默认图床设置为腾讯cos，之后打算用这个插件把图片转移到腾讯cos上，但是都失败了，错误信息为：迁移完成，图片迁移成功0张，迁移失败1张。之后我新建了一个markdown文件，只写了一个md格式的链接，尝试迁移图片，结果还是显示迁移失败

错误日志：
```
2019-08-28 23:18:10 [PicGo INFO] Before transform

2019-08-28 23:18:10 [PicGo INFO] Transforming...

2019-08-28 23:18:10 [PicGo INFO] Before upload

2019-08-28 23:18:10 [PicGo INFO] Uploading...

2019-08-28 23:18:10 [PicGo ERROR] Error: Upload failed
------Error Stack Begin------
Error: Upload failed
    at Object.handle (D:\PicGo\resources\app.asar\node_modules\picgo\dist\plugins\uploader\tcyun.js:114:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
-------Error Stack End-------

2019-08-28 23:18:10 [PicGo WARN] Please check your configuration, since no images migrated successfully in C:\Users\Chor\Desktop\新建文本文档.md

2019-08-28 23:18:10 [PicGo INFO] Success: 0 pics, Fail: 1 pics
```

**Comment by Chorer** [comment]
为什么不回复此issue？如果无法修复请关闭。

**Comment by Molunerfinn** [comment]
更新至1.2.0版本即可
