### ISSUE TITLE
在本地上传上传至Github报错 缺失Sha

### ISSUE THREAD

**Issue by Ruth-Seven** [PicGo/picgo-plugin-pic-migrater#47]
2022-05-31 10:01:06 [PicGo INFO] Before transform 
2022-05-31 10:01:06 [PicGo INFO] Transforming... Current transformer is [path] 
2022-05-31 10:01:06 [PicGo INFO] Before upload 
2022-05-31 10:01:06 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-05-31 10:01:06 [PicGo INFO] Uploading... Current uploader is [github] 
2022-05-31 10:01:07 [PicGo SUCCESS] 
https://raw.githubusercontent.com/Ruth-Seven/pic/master/img/3044562b475891f0d891ac95be4d78b5_720w.jpg 
2022-05-31 10:02:32 [PicGo INFO] Migrating... 
2022-05-31 10:02:32 [PicGo INFO] Before transform 
2022-05-31 10:02:32 [PicGo INFO] Transforming... Current transformer is [base64] 
2022-05-31 10:02:32 [PicGo INFO] Before upload 
2022-05-31 10:02:32 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-05-31 10:02:32 [PicGo INFO] Uploading... Current uploader is [github] 
2022-05-31 10:02:33 [PicGo WARN] failed 
2022-05-31 10:02:33 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 422 - {"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
    at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2022-05-31 10:02:33 [PicGo ERROR] 
------Error Stack Begin------
StatusCodeError: 422 - {"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
    at new StatusCodeError (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
-------Error Stack End------- 
2022-05-31 10:02:33 [PicGo WARN] Please check your configuration, since no images migrated successfully in /Users/ove/Downloads/印象笔记/操作系统中断.md 
2022-05-31 10:02:33 [PicGo INFO] Success: 0 pics, Fail: 5 pics 

可以查看

https://docs.github.com/rest/reference/repos#create-or-update-file-contents

**Comment by Molunerfinn** [comment]
这是因为你上传了同名文件到github上 才会有这个报错
