### ISSUE TITLE
图片上传到图床了，但是新的md文件中的地址没有被替换

### ISSUE THREAD

**Issue by systemcaller** [PicGo/picgo-plugin-pic-migrater#64]
原md文件地图片址： 
![image](https://github.com/user-attachments/assets/4604db72-a23b-4aa9-b22a-033d375535a5)
插件配置：
![image](https://github.com/user-attachments/assets/ccaf7e1d-656c-4b19-b799-14d63559765d)
选择文件执行后：
![image](https://github.com/user-attachments/assets/79262442-5449-4ab7-a07a-365589143834)

**Comment by colin4k** [comment]
我已提交了修复此问题的 pr，可以到我的仓库看看：
https://github.com/colin4k/picgo-plugin-pic-migrater

**Comment by wodepig** [comment]
插件的描述有问题. 上传成功后是把**源文件**的图片地址替换了.
新文件其实是备份文件,所以里面的图片还是本地的.你自己打开源文件看一眼就明白了,并不是bug

**Comment by colin4k** [comment]
> 插件的描述有问题. 上传成功后是把**源文件**的图片地址替换了. 新文件其实是备份文件,所以里面的图片还是本地的.你自己打开源文件看一眼就明白了,并不是bug

不是的，我确认过，主要问题是有一些图片的 url 不是以图片文件扩展名结尾，例如微信和知乎的都是这样，如下:
`https://mmbiz.qpic.cn/mmbiz_png/n8UWicng6vIA4usX2sOyd5NibTrl07M89U5MMpQsicyoiatWVlib95H1w1Sricw08C6oQ2PicufjA073In29F9zEY5vdg/640?wx_fmt=png`
这种就不会替换，所以我增加了正则表达式的匹配逻辑，对于这种也可以进行替换

**Comment by aqquser** [comment]
> 我已提交了修复此问题的 pr，可以到我的仓库看看： https://github.com/colin4k/picgo-plugin-pic-migrater

怎么使用啊？

**Comment by YVHU1** [comment]
我在七牛云用这个插件是正常的，现在换了图床后用此插件能正常上传到图床但生成的文件内图片地址没有被URL替换日志为[PicGo ERROR] [PicGo] Failed to delete temp file [object Object]: 
------Error Stack Begin------
TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received an instance of Object
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.relative (node:path:498:5)
    at F:\A PICGO\resources\app.asar\index.js:2:879426
    at Array.forEach (<anonymous>)
    at ci (F:\A PICGO\resources\app.asar\index.js:2:879391)
    at Object.upload (F:\A PICGO\resources\app.asar\index.js:2:882385)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Ii.upload (F:\A PICGO\resources\app.asar\index.js:2:890108)
    at async Migrater.migrate (C:\Users\86132\AppData\Roaming\picgo\node_modules\picgo-plugin-pic-migrater\dist\lib\Migrater.js:70:26)
-------Error Stack End-------

**Comment by Molunerfinn** [comment]
> 我在七牛云用这个插件是正常的，现在换了图床后用此插件能正常上传到图床但生成的文件内图片地址没有被URL替换日志为[PicGo ERROR] [PicGo] Failed to delete temp file [object Object]: ------Error Stack Begin------ TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received an instance of Object at new NodeError (node:internal/errors:371:5) at validateString (node:internal/validators:119:11) at Object.relative (node:path:498:5) at F:\A PICGO\resources\app.asar\index.js:2:879426 at Array.forEach () at ci (F:\A PICGO\resources\app.asar\index.js:2:879391) at Object.upload (F:\A PICGO\resources\app.asar\index.js:2:882385) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async Ii.upload (F:\A PICGO\resources\app.asar\index.js:2:890108) at async Migrater.migrate (C:\Users\86132\AppData\Roaming\picgo\node_modules\picgo-plugin-pic-migrater\dist\lib\Migrater.js:70:26) -------Error Stack End-------

问题已知，近期会修复

**Comment by Molunerfinn** [comment]
1.3.3 版本已经更新修复没有正确迁移的两种问题，可以查看更新日志：https://github.com/PicGo/picgo-plugin-pic-migrater/releases/tag/v1.3.3

至于 `[PicGo ERROR] [PicGo] Failed to delete temp file [object Object]:` 这个错误是 PicGo 客户端本体产生的，将会在 PicGo 本体的 2.4.1 版本里修复更新，感谢支持
